In [59]:
import pandas as pd
import numpy as np
async_http2 = pd.read_csv('http2asynctest.csv', delimiter=";")
async_http3 = pd.read_csv('http3asynctest.csv', delimiter=";")

mean_http2 = async_http2.mean()
min_http2 = async_http2.min()
max_http2 = async_http2.max()

mean_http3 = async_http3[async_http3["http_version"] == 3].mean()
min_http3 = async_http3[async_http3["http_version"] == 3].min()
max_http3 = async_http3[async_http3["http_version"] == 3].max()

print("All HTTP/2 requests: " + str(async_http2.shape[0]))
print("Mismatched HTTP/2 requests: " + str(async_http2[async_http2["http_version"] != 2].shape[0]))
print("Failed HTTP/2 requests: " + str(async_http2[async_http2["response_code"] != 200].shape[0]))
print("")
print("All HTTP/3 requests: " + str(async_http3.shape[0]))
print("Mismatched HTTP/3 requests: " + str(async_http3[async_http3["http_version"] != 3].shape[0]))
print("Failed HTTP/3 requests: " + str(async_http3[async_http3["response_code"] != 200].shape[0]))
pd.DataFrame(
  {
    "HTTP/2 Min": min_http2.values, 
    "HTTP/2 Mean": mean_http2.values, 
    "HTTP/2 Max": max_http2.values, 
    "HTTP/3 Min": min_http3.values,
    "HTTP/3 Mean": mean_http3.values,
    "HTTP/3 Max": max_http3.values
  },
  mean_http2.keys(),
  [
    "HTTP/2 Min",
    "HTTP/2 Mean",
    "HTTP/2 Max",
    "HTTP/3 Min",
    "HTTP/3 Mean",
    "HTTP/3 Max"
  ]
)

All HTTP/2 requests: 1000
Mismatched HTTP/2 requests: 0
Failed HTTP/2 requests: 0

All HTTP/3 requests: 1000
Mismatched HTTP/3 requests: 448
Failed HTTP/3 requests: 1

,HTTP/2 Min,HTTP/2 Mean,HTTP/2 Max,HTTP/3 Min,HTTP/3 Mean,HTTP/3 Max
response_code,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
http_version,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000
speed_download,0.000000,0.812000,13.000000,10.000000,28.358696,35.000000
speed_upload,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
time_starttransfer,0.293660,11.770661,91.398523,0.111264,0.142822,0.388517
time_pretransfer,0.186894,11.616789,91.329832,0.075846,0.092942,0.186938
time_appconnect,0.186814,11.616485,91.329329,0.073129,0.088961,0.183298
time_total,0.293680,11.770746,91.398629,0.111349,0.142945,0.388548
time_connect,0.049238,1.916400,11.043606,0.000000,0.000000,0.000000